const { book_hall, unapproved_bookings, upcoming_events, past_events, approve_booking, decline_booking } = require("./controllers/book")
const { create_new_hall, fetch_halls, fetch_hall, delete_hall, update_hall } = require("./controllers/hall")
const { register_user, login_user } = require("./controllers/user")

let route =require("express").Router()
route.post("/register",register_user)
route.post("/create-hall",create_new_hall)
route.post("/login",login_user)
route.post("/book-hall",book_hall)
route.get("/fetch-halls",fetch_halls)
route.get("/fetch-hall",fetch_hall)
route.post("/delete-hall",delete_hall)
route.get("/fetch-unapproved-bookings",unapproved_bookings)
route.get("/upcoming-events",upcoming_events)
route.get("/past-events",past_events)
route.get("/approve-booking",approve_booking)
route.get("/decline-booking",decline_booking)
route.put("/update-hall",update_hall)
module.exports=route